import org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget

import static co.touchlab.cklib.gradle.CompileToBitcode.Language.C

apply plugin: 'org.jetbrains.kotlin.multiplatform'
apply from: "$rootDir/addAllTargets.gradle"
apply from: "$rootDir/publish.gradle"
apply plugin: 'co.touchlab.cklib'
apply plugin: 'app.cash.burst'

kotlin {
	explicitApi()

	sourceSets {
		configureEach {
			languageSettings {
				optIn('kotlinx.cinterop.ExperimentalForeignApi')
			}
		}

		commonTest {
			dependencies {
				implementation libs.androidx.annotation
				implementation libs.assertk
				implementation libs.kotlin.test
				implementation libs.kotlinx.coroutines.test
			}
		}
	}

	def linkNativeDebugTests = tasks.register('linkNativeDebugTests')

	targets.withType(KotlinNativeTarget).configureEach {
		compilations.main.cinterops {
			create('mosaic') {
				header(file('src/commonMain/c/mosaic.h'))
				packageName('com.jakewharton.mosaic.tty')
				compilerOpts(
					'-std=gnu11',
					'-Wall',
					'-Wextra',
					'-Werror',
				)
			}
		}
		linkNativeDebugTests.configure {
			it.dependsOn(compilations.test.binariesTaskName)
		}
	}

	compilerOptions.freeCompilerArgs.add('-Xexpect-actual-classes')
}

cklib {
	config.kotlinVersion = libs.versions.kotlin.get()
	create('mosaic', file('src/commonMain/c'), ['main']) {
		it.srcDirs = files('src/commonMain/c')
		it.language = C
	}
}
